theme: jekyll-theme-slate
title: This is the personal homepage of Michelle Reimann, Computer Science student at University of Bayreuth (Germany)
description: What you will find here are short descriptions about myself and repositories related to my study.
plugins:
  - jemoji
url: "https://MichiMaxima.github.io/";
markdown: kramdown